mysite/blog/urls.py
from django.urls import URLPattern,path
from . import views

app_name= 'blog'

urlpatterns= [
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('addpost/',views.add_post,name='addpost'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog')),
]

mysite/blog/models.py
from ast import mod
import email
from telnetlib import STATUS
from unicodedata import name
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager,
#             self).get_queryset()\
#                 .filter(status='published')


class Post(models.Model):
        STATUS_CHOICES =(
            ('draft', 'Draft'),
            ('published', 'Published'),
        )

        title= models.CharField(max_length=250)
        slug= models.SlugField(max_length=1000,unique_for_date='publish',auto_created=True)
        author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
        body= models.TextField()
        publish = models.DateTimeField(default=timezone.now)
        created= models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now_add=True)
        status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
        tags= TaggableManager()

        # objects = models.Manager() # The default manager.
        # published = PublishedManager() # Our custom manager.
        class Meta:
            ordering= ('-publish',)
        def __str__(self):
            return self.title

        def get_absolute_url(self):
            return reverse('blog:post_detail',
                            args=[self.publish.year,
                                self.publish.month,
                                self.publish.day, self.slug])


class Comment(models.Model):
    post= models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')

    name= models.CharField(max_length=80)
    email= models.EmailField()
    body= models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)
    active= models.BooleanField(default=True)
    class Meta:
        ordering= ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import Comment, Post

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields= ('name', 'email', 'body')

class Addpost(forms.ModelForm):
    class Meta:
        model= Post
        fields= ['title','slug','author','body', 'publish','status','tags']

mysite/blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from datetime import datetime
from .models import *
from django.views.generic import ListView
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from .forms import *
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

def add_post(request):
    if request.method == 'POST':
        form = Addpost(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')
    else:
        form = Addpost()
        
    return render (request,'blog/add_post.html',{'form':form})

def post_list(request,tag_slug=None):
    object_list= Post.objects.all()


    #search
    object= request.GET.get('search')
    if object != '' and object is not None:
        object_list= object_list.filter(title__icontains= object)
    
    #tags
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug= tag_slug)
        object_list= object_list.filter(tags__in=[tag])
   
   #pages
    paginator= Paginator(object_list,3)
    page= request.GET.get('page')
    try:
        posts= paginator.page(page)
    except PageNotAnInteger:
        posts= paginator.page(1)
    except EmptyPage:
        posts= paginator.page(paginator.num_pages)
    return render(request, 'blog/list.html',{'page':page,'posts':posts,'tag':tag})

def post_detail(request,year,month,day,post):
    post= get_object_or_404(Post,slug=post,status='published',publish__year= year,publish__month= month, publish__day= day)

    comments = post.comments.filter(active=True)

    new_comment= None
    if request.method== 'POST':
        comment_form = CommentForm(data= request.POST)
        if comment_form.is_valid():
            new_comment= comment_form.save(commit=False)
            new_comment.post= post
            new_comment.save()
    else:
        comment_form= CommentForm()
    
    #similar posts
    post_tags_ids = post.tags.values_list('id',flat= True)
    similar_posts= Post.objects.filter(tags__in= post_tags_ids)\
        .exclude(id= post.id)
    similar_posts= similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags','-publish')[:4]

    return render(request,'blog/detail.html',{'post':post, 'comments':comments, 'new_comment': new_comment, 'comment_form': comment_form,'similar_posts':similar_posts})



def post_share(request,post_id):
   post = get_object_or_404(Post, id= post_id, status= 'published')
   sent= False

   



   if request.method== 'POST':
       form = EmailPostForm(request.POST)
       if form.is_valid():
           cd = form.cleaned_data
           post_url = request.build_absolute_uri(
               post.get_absolute_url())

           subject = f"{cd['name']} recommends you read"\
                f"{post.title}"
           message = f"Read {post.title} at {post_url}\n\n"\
                f"{cd['name']}\'s comments: {cd['comments']}"
           send_mail(subject, message, 'alimozzamandurjoy2@gmail.com',[cd['to']])
           sent= True
   else:
       form= EmailPostForm()
   return render(request, 'blog/share.html',{'post':post,'form': form,'sent': sent})
  

mysite/blog/templates/blog/add_post.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} My Blog {% endblock title %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <input type="submit" value="submit" >
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
</head>
<body>

    <div class="card m-3">
        <nav class="navbar navbar-light bg-light justify-content-between">
            <a class="navbar-brand  hover-shadow" href="{% url 'blog:post_list' %}">Home</a>
            
            
            
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit" >Search</button>
            </form>
        </nav>
    </div>
   

    <div id="content">
        {% block content %}
            
        {% endblock content %}
    </div>
    <div id="sidebar">
        <h2>Want to write a blog ?</h2> <br>
        <a href="{% url 'blog:addpost' %}" role="button">+Add New Blog</a>

    </div>
    <div id="content">
        {% block page %}
            
        {% endblock page %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>
</html>

mysite/blog/templates/blog/detail.html
{% extends "blog/base.html" %}


{% block content %}

{% load crispy_forms_tags %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
</p>
<h2>Similar Posts</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment {{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>Add a new comment</h2>
    <form method="post">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
{% endif %}
{% endblock content %}

mysite/blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %} My Blog {% endblock title %}


{% block content %}


<div class="card m-3 ">
    <div class="card-header  shadow p-3 mb-5 bg-white rounded">
        <h1>My Blog</h1>
    </div>
    <div class="card-body ">
        {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}
        {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}

            </a>

        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>


        <p class="date">
            Published{{ post.publish }} by {{ post.author }}
        </p>

        {{ post.body| truncatewords:30|linebreaks }}
        {% endfor %}
    </div>
</div>

{% include "blog/pagination.html" with page=posts %}
{% endblock content %}

mysite/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

mysite/blog/templates/blog/share.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Share a post{% endblock %}
{% block content %}
<div class="card ml-4">
    <div class="card-body">
        {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
        {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Send e-mail">
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}